export const MessageConstants = {
  PLACEHOLDER: {
    YOUR_NAME: 'Your name',
    YOUR_AGE: 'Your age',
    WEIGHT_KG: 'Your weight in kg',
  },
  ERROR: {
    GENERIC: 'Something went wrong. Please try again.',
    SAVE_PROFILE_FAILED: 'Failed to save user profile',
    SAVE_THEME_FAILED: 'Failed to save theme preference',
    SAVE_FOLLOW_SYSTEM_FAILED: 'Failed to save system theme preference',
    SAVE_MEAL_PLAN_FAILED: 'Failed to save meal plan',
    LOAD_USER_PROFILE_FAILED: 'Failed to load user profile',
    LOAD_THEME_FAILED: 'Failed to load theme preferences',
    LOAD_ONBOARDING_FAILED: 'Failed to load onboarding status',
    MEAL_PLAN_LOAD_FAILED: 'Failed to load meal plan',
    MEAL_PLAN_NOT_FOUND: 'Meal plan not found',
    RESET_FAILED: 'Failed to reset app',
    GENERATE_MEAL_PLAN_FAILED:
      'Failed to generate meal plan. Please check your API key and try again.',
    CONTEXT_ERROR: {
      ONBOARDING: 'useOnboarding must be used within an OnboardingProvider',
      THEME: 'useTheme must be used within a ThemeProvider',
    },
  },

  SUCCESS: {
    MEAL_PLAN_GENERATED: 'Meal plan generated successfully!',
    PROFILE_UPDATED: 'Your profile has been updated successfully!',
  },

  ALERT_TITLE: {
    ERROR: 'Error',
    SUCCESS: 'Success',
    CONFIRM: 'Confirm',
    VERSION: 'Version',
    INVALID_INPUT: 'Invalid Input',
    INVALID_NAME: 'Invalid Name',
  },

  ALERT_MESSAGE: {
    RESET_APP:
      'Are you sure you want to reset the app? All your data will be lost.',
    RESET_FAILED: 'Failed to reset app. Please try again.',
    PROFILE_NOT_FOUND: 'User profile not found. Please restart the app.',
    APP_VERSION: 'mealPlanner v1.0.0',
    ENTER_VALID_VALUE: 'Please enter a valid value.',
    ENTER_NAME: 'Please enter your name.',
  },

  BUTTON: {
    CANCEL: 'Cancel',
    CONFIRM: 'Confirm',
    RESET: 'Reset',
    GO_BACK: 'Go Back',
    GENERATE_MEAL_PLAN: 'Generate Meal Plan',
    BACK: 'Back',
    NEXT: 'Next',
    FINISH: 'Finish',
    SAVE_CHANGES: 'Save Changes',
  },

  INPUT_TYPE: {
    TEXT: 'text',
    NUMBER: 'number',
    SELECT: 'select',
  },

  LABEL: {
    DARK_MODE: 'Dark Mode',
    FOLLOW_SYSTEM_THEME: 'Follow System Theme',
    APP_VERSION: 'App Version',
    RESET_APP: 'Reset App',
    SETTINGS: 'Settings',
    MEAL_PLAN_HISTORY: 'Meal Plan History',
    TOTAL_CALORIES: 'Total Calories',
    BREAKFAST: 'Breakfast',
    LUNCH: 'Lunch',
    DINNER: 'Dinner',
    TELL_US_YOUR_NAME: 'Tell us your name',
    AGE_QUESTION: 'How old are you?',
    GENDER_QUESTION: 'What is your gender?',
    WEIGHT_QUESTION: 'What is your weight?',
    DIET_PREFERENCE: 'What is your dietary preference?',
    CUISINE_PREFERENCE: 'What type of cuisine do you prefer?',
    PREFERRED_CUISINE: 'Preferred  cuisine',
    GOAL_QUESTION: 'What is your goal?',
    MALE: 'Male',
    FEMALE: 'Female',
    OTHER: 'Other',
    VEGETARIAN: 'Vegetarian',
    NON_VEGETARIAN: 'Non-Vegetarian',
    INDIAN_CUISINE: 'Indian',
    WESTERN_CUISINE: 'Western',
    MEDITERRANEAN_CUISINE: 'Mediterranean',
    ASIAN_CUISINE: 'Asian',
    MIXED_CUISINE: 'Mixed / No Preference',
    LOSE_WEIGHT: 'Lose Weight',
    MAINTAIN_WEIGHT: 'Maintain Weight',
    GAIN_WEIGHT: 'Gain Weight',
    AGE: 'Age',
    WEIGHT: 'Weight',
    DIET: 'Diet',
    CUISINE: 'Cuisine',
    GENDER: 'Gender',
    GOAL: 'Goal',
    NAME: 'Name',
    PERSONAL_INFO: 'Personal Information',
  },

  UI_TEXT: {
    WELCOME_PREFIX: 'Welcome, ',
    WELCOME_SUBTITLE: "Let's create your personalized meal plan",
    YOUR_PROFILE: 'Your Profile',
    INGREDIENTS: 'Ingredients:',
    NO_MEAL_PLANS: 'No meal plans yet',
    GENERATE_INSTRUCTION:
      'Generate a meal plan from the Home tab to see it here.',
    APP_FOOTER: 'Made with ❤️ by mealPlanner Team',
    POWERED_BY: 'Powered by AI',
    CALORIES_SUFFIX: 'kcal',
    RESET_DISCLAIMER:
      '* Resetting the app will clear all your data including your profile and meal plans.',
    APP_NAME: 'mealPlanner',
    APP_SUBTITLE: 'Your AI Meal Planner',
    YEARS: 'years',
    KG: 'kg',
    LOADING: 'Loading...',
    EDIT_PROFILE: 'Edit Profile',
  },
};
